directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_260 #Ensure no security groups allow ingress from 0.0.0.0:0 to port 80
