directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV2_AWS_28 #Ensure public facing ALB are protected by WAF
- CKV_AWS_111 #Ensure IAM policies does not allow write access without constraints
- CKV_AWS_158 #Ensure that CloudWatch Log Group is encrypted by KMS
