directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV2_AWS_20 #Ensure that ALB redirects HTTP requests into HTTPS ones
- CKV2_AWS_28 #Ensure public facing ALB are protected by WAF
