directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_TF_1 # Ensure Terraform module sources use a commit hash
- CKV_TF_2 # Ensure Terraform module sources use a tag with a version number
- CKV2_AWS_5 # Ensure that Security Groups are attached to another
- CKV2_AWS_20 # Ensure that ALB redirects HTTP requests into HTTPS ones
- CKV2_AWS_28 # Ensure public facing ALB are protected by WAF
- CKV_AWS_150 # Ensure that Load Balancer has deletion protection enabled
- CKV_AWS_152 # Ensure that Load Balancer (Network/Gateway) has cross-zone load balancing enabled
- CKV_AWS_260 # Ensure no security groups allow ingress from 0.0.0.0:0 to port 80
- CKV_AWS_261 # Ensure HTTP HTTPS Target group defines Healthcheck
- CKV_AWS_336 # Ensure ECS containers are limited to read-only access to root filesystems
- CKV_AWS_338 # Ensure CloudWatch log groups retains logs for at least 1 year
