directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_260 #Ensure no security groups allow ingress from 0.0.0.0:0 to port 80
- CKV_AWS_336 #Ensure ECS containers are limited to read-only access to root filesystems
- CKV_AWS_338 #Ensure CloudWatch log groups retains logs for at least 1 year
- CKV2_AWS_5 #Ensure that Security Groups are attached to another 
- CKV_AWS_150 #Ensure that Load Balancer has deletion protection enabled